version: '3.9'

services:
  app:
    restart: on-failure
    build: ./app
    
    ports:
      - '81:5001'
    
    volumes:
    - ./app/src/:/usr/app/src/

  nginx:
    build: ./nginx
    ports:
    - '80:80'
    - '443:443'
    depends_on:
    - app